devpi:
    build: .
    environment:
        - HOSTNAME=localhost:3141
        - DEVPI_PASSWORD=''
        - DEVPICLIENT_CLIENTDIR=/tmp/devpi-client
        - DEVPISERVER_SERVERDIR=/srv/devpi/devpi
    volumes:
        - ./devpi:/srv/devpi/devpi
    ports:
        - 3141:3141
    user: devpi
